# Generated by Django 5.2.14 on 2026-05-12 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(blank=True, max_length=100)),
                ('default', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'categories',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Param',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('value', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'params',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds_category', models.CharField(max_length=255)),
                ('ds_subcategory', models.CharField(blank=True, max_length=255)),
                ('details', models.TextField(blank=True)),
                ('dt_entry', models.DateField()),
                ('vl_entry', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.BooleanField(default=False)),
                ('fixed', models.BooleanField(default=False)),
                ('checked', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='finance.category')),
            ],
            options={
                'db_table': 'entries',
                'ordering': ['dt_entry'],
            },
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facts', to='finance.entry')),
            ],
            options={
                'db_table': 'facts',
            },
        ),
    ]
