# Generated by Django 5.2.14 on 2026-05-18 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='export_warning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='export_warning_msg',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
